
global:
  scrape_interval: 60s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 60s # Evaluate rules every 15 seconds. The default is every 1 minute.

alerting:
  alertmanagers:
    - static_configs:
        - targets:
rule_files:
scrape_configs:

  - job_name: 'blackbox'
    metrics_path: /probe
    params:
        module: [http_404]
    static_configs:
        - targets:
            - https://hbogo.globe.com.ph
            - https://amazonprimevideo.globe.com.ph
            - https://amazonkindleunlimited.globe.com.ph
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 172.31.17.199:9115  # The blackbox exporter's real hostname:port. use ifconfig

